# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: (M) Blog
email: mank.pclos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  One - Linux & Music & Open Source Lover.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.m-opensource.eu" # the base hostname & protocol for your site
twitter_username: mank_unix
github_username:  mank1

paginate: 10

gaaccount: ''

highlighter: rouge

gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
