# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mank One Blog
email: Mank@pclinuxos.cz
description: > # this means to ignore newlines until "baseurl:"
  Mank One - Linux & Music & OpenSource Lover.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.m-opensource.eu" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mank1

gaaccount: ''

# Build settings
#markdown: kramdown

highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
